# Generated by Django 5.1.3 on 2025-05-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Familya')),
                ('age', models.IntegerField(blank=True, default=0, null=True, verbose_name='Yosh')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'TeacherModel',
                'verbose_name_plural': 'TeacherModels',
                'db_table': 'teacher',
            },
        ),
    ]
