# Generated by Django 5.1.3 on 2025-05-06 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='bot.categorymodel', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nomi'),
        ),
    ]
