# Generated by Django 5.1.3 on 2025-05-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_teachermodel_category_alter_categorymodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('user_id', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Telegram id')),
            ],
            options={
                'verbose_name': 'UserModel',
                'verbose_name_plural': 'UserModels',
                'db_table': 'user',
            },
        ),
    ]
