# Generated by Django 5.1.3 on 2025-05-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi ?'),
        ),
    ]
