# Generated by Django 5.1.3 on 2025-05-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_teachermodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_id',
            field=models.BigIntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Telegram id'),
        ),
    ]
