# Generated by Django 5.1.3 on 2025-05-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_teachermodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachermodel',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='last_name',
        ),
    ]
